echo "> é usado para redirecionar para a saida"
echo "exemplo: cat texto1.txt>texto.txt"
echo ">> é usado para redirecionar para o fim do arquivo"
echo " exemplo: cat texto1.txt>>texto.txt"
echo "2> é usado para redirecionar a saida de erros"
echo "exemplo: ls diretorioinexistente 2> /dev/null"
echo "2>> é usado para  redirecionar a saida de erro para um arquivo acrescentando o conteudo no final do arquivo"
echo "exemplo: ls diretorioinexistente 2>> ./erros.txt"
echo "&> é usado para direciona mensagem de erro e de acerto, para um arquivo,sobrescrevendo tudo que há nele."
echo "exemplo: ls arquivoduvidoso &> /dev/null"
echo "&>> é usado para redirecionar a saida de erro  e de acerto, para um arquivo sem sobrescrever nele."
echo "exemplo: ls arquivoduvidoso &>> ./erroseacertos.txt"
echo "< é usado para redirecionar para a entrada"
echo "exemplo:  mail <conteudodoemail"
echo "<< é usado para redireciona para a entrada e mantem a entrada aberta ate que seja digitado algum caractere"
echo "exemplo: mail loucura@loucura.com.br << fim"
echo" <<< é usado para redirecionar varias variaveis/saidas de um comando para a entrada de outro"
echo "exemplo:  read first second <<< hello world echo $second $first "
echo "| é usado para  redirecionar a saida de um comando para a entrada de  outro"
echo "exemplo: ls arq |wc -l"
